"""Tests for the joint prefactor-excursion Monte Carlo (v2.346)."""

from experiments.qnm_prefactor_joint_excursion import run

# one modest-n run shared across tests (the full-n artifact is generated by main())
RES = run(n_samples=300, seed=1)


def test_all_checks_pass():
    assert RES["all_checks_pass"] is True
    for k, v in RES["consistency_checks"].items():
        assert v is True, k


def test_joint_fraction_is_a_probability():
    assert 0.0 <= RES["joint_feasible_fraction"] <= 1.0
    assert RES["n_feasible"] > 0  # the constructed point is a genuine feasible point, not knife-edge


def test_joint_more_marginal_than_single_axis():
    # the whole point: joint feasibility is well below the optimistic single-axis OAT figure
    assert RES["joint_feasible_fraction"] < RES["min_single_axis_oat_fraction"]


def test_joint_near_independence_estimate():
    # breaks act through distinct constraints -> joint ~ product of per-axis fractions (within sampling error)
    assert abs(RES["joint_feasible_fraction"] - RES["oat_independence_estimate"]) < 0.15


def test_top_violators_are_load_bearing_constraints():
    load_bearing = {
        "generalized_anomaly_inflow", "bnossw_monogamy", "cft_flat_space_bound",
        "complexity_cutoff", "matter_s3_positivity", "scalar_wgc"}
    assert RES["top_violators"], "expected some violations under joint variation"
    for v in RES["top_violators"]:
        assert v["constraint"] in load_bearing, v["constraint"]


def test_finding_and_scope_flags():
    f = RES["finding"].lower()
    assert "marginal" in f and "joint" in f
    assert "v2.345" in f
    sc = RES["honest_scope"].lower()
    assert "sampling measure" in sc or "uniform-independent" in sc
    assert "toy basis" in sc
